import 'dotenv/config';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import express from 'express';
import session from 'express-session';
import {ImapFlow} from 'imapflow';
import {simpleParser} from 'mailparser';
import nodemailer from 'nodemailer';

const app=express();
const isProd=process.env.NODE_ENV==='production';
const isVercel=!!process.env.VERCEL;
const aiStorePath=path.join(process.cwd(),'data','ai.json');
const key=crypto.createHash('sha256').update(process.env.MAIL_ENCRYPTION_KEY||process.env.SESSION_SECRET||'development-only-key').digest();
let savedAiKey=null;
function seal(value){const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',key,iv);const body=Buffer.concat([cipher.update(JSON.stringify(value),'utf8'),cipher.final()]);return {iv:iv.toString('base64'),tag:cipher.getAuthTag().toString('base64'),body:body.toString('base64')};}
function open(value){const decipher=crypto.createDecipheriv('aes-256-gcm',key,Buffer.from(value.iv,'base64'));decipher.setAuthTag(Buffer.from(value.tag,'base64'));return JSON.parse(Buffer.concat([decipher.update(Buffer.from(value.body,'base64')),decipher.final()]).toString('utf8'));}
function readCookie(req,name){try{const raw=String(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(`${name}=`))?.slice(name.length+1);return raw?open(JSON.parse(Buffer.from(decodeURIComponent(raw),'base64url').toString('utf8'))):null}catch{return null}}
function writeCookie(res,name,value){const encoded=Buffer.from(JSON.stringify(seal(value))).toString('base64url');res.append('Set-Cookie',`${name}=${encodeURIComponent(encoded)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=31536000${isProd?'; Secure':''}`)}
function clearCookie(res,name){res.append('Set-Cookie',`${name}=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0${isProd?'; Secure':''}`)}
try{if(fs.existsSync(aiStorePath))savedAiKey=open(JSON.parse(fs.readFileSync(aiStorePath,'utf8'))).apiKey;}catch(e){console.warn('Saved AI setup could not be restored:',e.message);}
function saveAiKey(apiKey){if(isVercel)return;savedAiKey=apiKey;fs.mkdirSync(path.dirname(aiStorePath),{recursive:true});fs.writeFileSync(aiStorePath,JSON.stringify(seal({apiKey})),{mode:0o600});}
const configuredAiKey=req=>process.env.OPENAI_API_KEY||readCookie(req,'vedoy.ai')?.apiKey||(!isVercel?savedAiKey:null);
app.set('trust proxy',1);
app.use(express.json({limit:'24mb'}));
app.use(session({name:'vedoy.sid',secret:process.env.SESSION_SECRET||'change-this-before-production',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:isProd,maxAge:1000*60*60*12}}));

const safe=(value='')=>String(value).replace(/[\r\n]/g,'').trim();
const cleanText=(value='')=>String(value)
 .replace(/<!--\[if[\s\S]*?<!\[endif\]-->/gi,' ')
 .replace(/<!--[\s\S]*?-->/g,' ')
 .replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ')
 .replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ')
 .replace(/<[^>]+>/g,' ')
 .replace(/\s+/g,' ')
 .trim();
const colorFor=value=>['#657c86','#b79b79','#829175','#cf7258','#9a6e68'][crypto.createHash('sha1').update(value).digest()[0]%5];
const initials=value=>value.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()||'?';
const envMail=()=>process.env.MAIL_EMAIL&&process.env.MAIL_PASSWORD?{email:process.env.MAIL_EMAIL,password:process.env.MAIL_PASSWORD,imapHost:process.env.MAIL_IMAP_HOST||'imap.domeneshop.no',imapPort:Number(process.env.MAIL_IMAP_PORT||993),smtpHost:process.env.MAIL_SMTP_HOST||'smtp.domeneshop.no',smtpPort:Number(process.env.MAIL_SMTP_PORT||465),imapSecure:true,smtpSecure:Number(process.env.MAIL_SMTP_PORT||465)===465}:null;
const accountIdFor=mail=>crypto.createHash('sha256').update(`${safe(mail.email).toLowerCase()}|${safe(mail.imapHost).toLowerCase()}`).digest('hex').slice(0,16);
const accountCookieName=id=>`vedoy.mail.${String(id).replace(/[^a-f0-9]/g,'').slice(0,16)}`;
const accountIndex=req=>{const value=readCookie(req,'vedoy.accounts');return value&&Array.isArray(value.accounts)?value:{activeId:null,accounts:[]}};
const accountSummary=(mail,id=accountIdFor(mail))=>({id,email:mail.email,host:mail.imapHost,label:mail.email.split('@')[0]||mail.email});
function storedAccounts(req){const index=accountIndex(req);const accounts=index.accounts.map(meta=>({meta,mail:readCookie(req,accountCookieName(meta.id))})).filter(x=>x.mail);const legacy=readCookie(req,'vedoy.mail');if(legacy&&!accounts.some(x=>x.meta.id===accountIdFor(legacy)))accounts.push({meta:accountSummary(legacy),mail:legacy});return{activeId:index.activeId||accounts[0]?.meta.id||null,accounts};}
const configFrom=req=>req.session?.mail||(()=>{const stored=storedAccounts(req);return stored.accounts.find(x=>x.meta.id===stored.activeId)?.mail||stored.accounts[0]?.mail||envMail()})()||envMail();
function client(req){const c=configFrom(req);if(!c)throw Object.assign(new Error('Sign in required'),{status:401});return new ImapFlow({host:c.imapHost,port:Number(c.imapPort||993),secure:c.imapSecure!==false,auth:{user:c.email,pass:c.password},logger:false});}
function requireMail(req,res,next){if(!configFrom(req))return res.status(401).json({error:'Sign in required'});next();}
function fail(res,error){const status=error.status||500;console.error('Mailbox request error:',error?.stack||error);res.status(status).json({error:status===500?'Mailbox request failed':error.message});}
const folderSpecialUse={Inbox:'\\Inbox',Starred:'\\Inbox',Snoozed:'\\Inbox',Sent:'\\Sent',Drafts:'\\Drafts',Archive:'\\Archive',Trash:'\\Trash'};
const folderAliases={Sent:['sent','sent items','sent messages'],Drafts:['drafts'],Archive:['archive','archives'],Trash:['trash','deleted items','deleted messages']};
async function mailboxName(clientInstance,folder,{allowMissing=false}={}){
 const requested=safe(folder)||'Inbox';
 if(requested==='Inbox'||requested==='Starred'||requested==='Snoozed')return 'INBOX';
 const mailboxes=await clientInstance.list();
 const specialUse=folderSpecialUse[requested];
 const specialMatch=specialUse&&mailboxes.find(mailbox=>mailbox.specialUse===specialUse);
 if(specialMatch)return specialMatch.path;
 const names=new Set([requested,...(folderAliases[requested]||[])].map(name=>name.toLocaleLowerCase('en-US')));
 const nameMatch=mailboxes.find(mailbox=>names.has(String(mailbox.path).toLocaleLowerCase('en-US'))||names.has(String(mailbox.name||'').toLocaleLowerCase('en-US')));
 if(nameMatch)return nameMatch.path;
 if(allowMissing)return null;
 throw Object.assign(new Error(`Mappen «${requested}» finnes ikke hos e-postleverandøren.`),{status:404});
}
function attachmentName(value='attachment'){return (safe(value)||'attachment').replace(/[\\/:*?"<>|]/g,'_').slice(0,180);}
function encodedFilename(value){return encodeURIComponent(value).replace(/[!'()*]/g,char=>`%${char.charCodeAt(0).toString(16).toUpperCase()}`);}
function attachmentMeta(attachment,index){const contentType=safe(attachment.contentType)||'application/octet-stream';return{id:index,name:attachmentName(attachment.filename),size:Number(attachment.size||attachment.content?.length||0),contentType,contentId:safe(attachment.contentId).replace(/^<|>$/g,''),disposition:safe(attachment.contentDisposition)||'attachment',isImage:contentType.startsWith('image/')};}
function normalize(envelope,uid,flags=[],preview='') {const from=envelope?.from?.[0]||{};const name=from.name||from.address||'Unknown sender';return {id:String(uid),from:name,email:from.address||'',subject:envelope?.subject||'(no subject)',preview:cleanText(preview).slice(0,180),time:new Intl.DateTimeFormat('en',{hour:'2-digit',minute:'2-digit'}).format(envelope?.date||new Date()),date:new Intl.DateTimeFormat('en',{dateStyle:'medium',timeStyle:'short'}).format(envelope?.date||new Date()),unread:!flags.has('\\Seen'),starred:flags.has('\\Flagged'),avatar:initials(name),color:colorFor(name),labels:[]};}

app.post('/api/auth/login',async(req,res)=>{try{const body=req.body||{};const smtpPort=Number(body.smtpPort||process.env.MAIL_SMTP_PORT||465);const mail={email:safe(body.email),password:String(body.password||''),imapHost:safe(body.imapHost||process.env.MAIL_IMAP_HOST),imapPort:Number(body.imapPort||process.env.MAIL_IMAP_PORT||993),smtpHost:safe(body.smtpHost||process.env.MAIL_SMTP_HOST),smtpPort,imapSecure:body.imapSecure!==false,smtpSecure:body.smtpSecure===undefined?smtpPort===465:body.smtpSecure===true};if(!mail.email||!mail.password||!mail.imapHost||!mail.smtpHost)return res.status(400).json({error:'Email, password, IMAP host and SMTP host are required'});const c=new ImapFlow({host:mail.imapHost,port:mail.imapPort,secure:mail.imapSecure,auth:{user:mail.email,pass:mail.password},logger:false});await c.connect();await c.logout();const id=accountIdFor(mail),stored=storedAccounts(req),existing=stored.accounts.map(x=>x.meta).filter(x=>x.id!==id);if(existing.length>=5)return res.status(400).json({error:'Du kan ha opptil fem e-postkontoer i denne versjonen.'});const accounts=[...existing,accountSummary(mail,id)];req.session.mail=mail;writeCookie(res,accountCookieName(id),mail);writeCookie(res,'vedoy.accounts',{activeId:id,accounts});clearCookie(res,'vedoy.mail');res.json({email:mail.email,id,accounts,activeId:id});}catch(e){console.error('IMAP login error:',e.message);res.status(401).json({error:'Kunne ikke koble til. Kontroller e-postinnstillingene eller bruk et app-passord.'});}});
app.get('/api/accounts',(req,res)=>{const stored=storedAccounts(req),env=envMail();let accounts=stored.accounts.map(x=>x.meta),activeId=stored.activeId;if(!accounts.length&&env){const meta=accountSummary(env);accounts=[meta];activeId=meta.id}res.json({accounts,activeId});});
app.post('/api/accounts/:id/activate',(req,res)=>{const stored=storedAccounts(req),target=stored.accounts.find(x=>x.meta.id===req.params.id);if(!target)return res.status(404).json({error:'E-postkontoen finnes ikke.'});req.session.mail=target.mail;writeCookie(res,'vedoy.accounts',{activeId:target.meta.id,accounts:stored.accounts.map(x=>x.meta)});res.json({activeId:target.meta.id,email:target.meta.email});});
app.delete('/api/accounts/:id',(req,res)=>{const stored=storedAccounts(req),target=stored.accounts.find(x=>x.meta.id===req.params.id);if(!target)return res.status(404).json({error:'E-postkontoen finnes ikke.'});const remaining=stored.accounts.filter(x=>x.meta.id!==req.params.id),activeId=stored.activeId===req.params.id?(remaining[0]?.meta.id||null):stored.activeId;clearCookie(res,accountCookieName(req.params.id));clearCookie(res,'vedoy.mail');writeCookie(res,'vedoy.accounts',{activeId,accounts:remaining.map(x=>x.meta)});req.session.mail=remaining.find(x=>x.meta.id===activeId)?.mail||null;res.json({accounts:remaining.map(x=>x.meta),activeId});});
app.post('/api/auth/restore',(req,res)=>{const mail=configFrom(req);if(!mail)return res.status(404).json({error:'No mailbox has been configured yet'});req.session.mail=mail;const stored=storedAccounts(req);if(!stored.accounts.length){const id=accountIdFor(mail),accounts=[accountSummary(mail,id)];writeCookie(res,accountCookieName(id),mail);writeCookie(res,'vedoy.accounts',{activeId:id,accounts});clearCookie(res,'vedoy.mail')}res.json({email:mail.email});});
app.post('/api/auth/logout',(req,res)=>{req.session.destroy(()=>res.status(204).end())});
app.delete('/api/auth/forget',(req,res)=>{try{for(const account of storedAccounts(req).accounts)clearCookie(res,accountCookieName(account.meta.id));clearCookie(res,'vedoy.accounts');clearCookie(res,'vedoy.mail');req.session.destroy(()=>res.status(204).end());}catch(e){fail(res,e);}});
app.get('/api/health',(req,res)=>{const stored=storedAccounts(req),mail=configFrom(req);res.json({connected:!!mail,configured:!!mail,email:mail?.email||null,accountCount:stored.accounts.length||(mail?1:0),activeId:stored.activeId})});
app.get('/api/messages',requireMail,async(req,res)=>{let c;try{c=client(req);await c.connect();const folder=await mailboxName(c,req.query.folder,{allowMissing:true});if(!folder)return res.json({messages:[],total:0,folder:null,unavailable:true});const lock=await c.getMailboxLock(folder,{readOnly:true});try{const total=c.mailbox.exists;if(!total)return res.json({messages:[],total:0,folder});const start=Math.max(1,total-49);const records=[];for await(const m of c.fetch(`${start}:*`,{uid:true,envelope:true,flags:true,source:{start:0,maxLength:300}})){let preview='';try{preview=(await simpleParser(m.source)).text||'';}catch{}records.push(normalize(m.envelope,m.uid,m.flags,preview));}res.json({messages:records.reverse(),total,folder});}finally{lock.release();}}catch(e){fail(res,e);}finally{if(c?.usable)await c.logout();}});
app.get('/api/messages/:uid',requireMail,async(req,res)=>{let c;try{c=client(req);await c.connect();const folder=await mailboxName(c,req.query.folder);const lock=await c.getMailboxLock(folder);try{const m=await c.fetchOne(req.params.uid,{uid:true,envelope:true,flags:true,source:true},{uid:true});if(!m)return res.status(404).json({error:'Message not found'});const parsed=await simpleParser(m.source);const html=typeof parsed.html==='string'?parsed.html.slice(0,1_000_000):null;const text=(parsed.text||cleanText(html||'')).slice(0,500_000);if(req.query.markSeen!=='false')await c.messageFlagsAdd(req.params.uid,['\\Seen'],{uid:true});const attachments=(parsed.attachments||[]).map(attachmentMeta);res.json({...normalize(m.envelope,m.uid,m.flags,text),unread:req.query.markSeen==='false'?!m.flags.has('\\Seen'):false,body:text,html,attachments,hasContent:!!(text||html||attachments.length)});}finally{lock.release();}}catch(e){fail(res,e);}finally{if(c?.usable)await c.logout();}});
app.get('/api/messages/:uid/attachments/:attachmentId',requireMail,async(req,res)=>{let c;try{const attachmentId=Number(req.params.attachmentId);if(!Number.isInteger(attachmentId)||attachmentId<0)return res.status(400).json({error:'Invalid attachment'});c=client(req);await c.connect();const folder=await mailboxName(c,req.query.folder);const lock=await c.getMailboxLock(folder,{readOnly:true});try{const m=await c.fetchOne(req.params.uid,{source:true},{uid:true});if(!m)return res.status(404).json({error:'Message not found'});const parsed=await simpleParser(m.source);const attachment=(parsed.attachments||[])[attachmentId];if(!attachment)return res.status(404).json({error:'Attachment not found'});const content=Buffer.isBuffer(attachment.content)?attachment.content:Buffer.from(attachment.content||'');if(content.length>25*1024*1024)return res.status(413).json({error:'Attachment is larger than the 25 MB preview limit'});const meta=attachmentMeta(attachment,attachmentId),fallbackName=meta.name.replace(/[^\x20-\x7e]/g,'_').replace(/"/g,'');const inline=req.query.download!=='1'&&(meta.isImage||meta.disposition==='inline');res.set({'Content-Type':meta.contentType,'Content-Length':String(content.length),'Content-Disposition':`${inline?'inline':'attachment'}; filename="${fallbackName}"; filename*=UTF-8''${encodedFilename(meta.name)}`,'Cache-Control':'private, max-age=120','X-Content-Type-Options':'nosniff'});res.send(content);}finally{lock.release();}}catch(e){fail(res,e);}finally{if(c?.usable)await c.logout();}});
app.post('/api/messages/:uid/star',requireMail,async(req,res)=>{let c;try{c=client(req);await c.connect();const folder=await mailboxName(c,req.body.folder);const lock=await c.getMailboxLock(folder);try{if(req.body.starred)await c.messageFlagsAdd(req.params.uid,['\\Flagged'],{uid:true});else await c.messageFlagsRemove(req.params.uid,['\\Flagged'],{uid:true});res.status(204).end();}finally{lock.release();}}catch(e){fail(res,e);}finally{if(c?.usable)await c.logout();}});
app.post('/api/messages/:uid/seen',requireMail,async(req,res)=>{let c;try{c=client(req);await c.connect();const folder=await mailboxName(c,req.body.folder);const lock=await c.getMailboxLock(folder);try{if(req.body.seen)await c.messageFlagsAdd(req.params.uid,['\\Seen'],{uid:true});else await c.messageFlagsRemove(req.params.uid,['\\Seen'],{uid:true});res.status(204).end();}finally{lock.release();}}catch(e){fail(res,e);}finally{if(c?.usable)await c.logout();}});
app.post('/api/messages/:uid/move',requireMail,async(req,res)=>{let c;try{c=client(req);await c.connect();const source=await mailboxName(c,req.body.folder);const dest=await mailboxName(c,req.body.destination);const lock=await c.getMailboxLock(source);try{await c.messageMove(req.params.uid,dest,{uid:true});res.status(204).end();}finally{lock.release();}}catch(e){fail(res,e);}finally{if(c?.usable)await c.logout();}});
app.get('/api/ai/status',(req,res)=>res.json({configured:!!configuredAiKey(req),model:process.env.OPENAI_MODEL||'gpt-5.6-luna'}));
app.post('/api/ai/config',requireMail,(req,res)=>{const apiKey=String(req.body?.apiKey||'').trim();if(apiKey.length<20)return res.status(400).json({error:'Enter a valid OpenAI API key'});writeCookie(res,'vedoy.ai',{apiKey});saveAiKey(apiKey);res.json({configured:true});});
app.post('/api/ai/reply',requireMail,async(req,res)=>{try{const apiKey=configuredAiKey(req);if(!apiKey)return res.status(503).json({error:'Set up an OpenAI API key first',needsKey:true});const subject=safe(req.body?.subject).slice(0,500),sender=safe(req.body?.sender).slice(0,500),tone=safe(req.body?.tone||'Professional and warm').slice(0,100),notes=String(req.body?.notes||'').trim().slice(0,4000),message=String(req.body?.message||'').trim().slice(0,40000);if(!message)return res.status(400).json({error:'Open the email before generating a reply'});const safetyIdentifier=`vedoy_${crypto.createHash('sha256').update(configFrom(req)?.email||'local-user').digest('hex').slice(0,32)}`;const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5.6-luna',store:false,safety_identifier:safetyIdentifier,reasoning:{effort:'low'},text:{verbosity:'low'},max_output_tokens:900,instructions:'Draft a ready-to-edit email reply. Write in the same language as the received email unless the user notes request another language. Follow the requested tone. Be concise, natural, accurate, and professional. Do not invent facts, commitments, dates, prices, attachments, or actions. Return only the reply body, with no analysis, labels, markdown fences, or subject line.',input:`Sender: ${sender}\nSubject: ${subject}\nRequested tone: ${tone}\nUser notes: ${notes||'None'}\n\nReceived email:\n${message}`})});const result=await response.json();if(!response.ok){console.error('OpenAI reply error:',result?.error?.message||response.status);return res.status(response.status===401?401:502).json({error:response.status===401?'The OpenAI API key was rejected':'AI draft could not be generated'});}const draft=String(result.output_text||result.output?.flatMap(item=>item.content||[]).filter(item=>item.type==='output_text').map(item=>item.text).join('\n')||'').trim();if(!draft)return res.status(502).json({error:'AI returned an empty draft'});res.json({draft});}catch(e){console.error('AI draft error:',e.message);res.status(500).json({error:'AI draft could not be generated'});}});
app.post('/api/send',requireMail,async(req,res)=>{try{const {to,subject,text,html,attachments=[]}=req.body||{};if(!safe(to)||!safe(subject)||!(text||html))return res.status(400).json({error:'Recipient, subject and message are required'});if(!Array.isArray(attachments)||attachments.length>3)return res.status(400).json({error:'A maximum of three attachments is allowed'});const checked=attachments.map(a=>{const content=String(a.content||'');if(content.length>7_000_000)throw Object.assign(new Error(`${safe(a.filename)||'Attachment'} is too large`),{status:400});return{filename:safe(a.filename)||'attachment',contentType:safe(a.contentType)||'application/octet-stream',content:Buffer.from(content,'base64')}});const m=configFrom(req);const transport=nodemailer.createTransport({host:m.smtpHost,port:m.smtpPort,secure:m.smtpSecure,auth:{user:m.email,pass:m.password}});await transport.sendMail({from:m.email,to:safe(to),subject:safe(subject),text:String(text||''),html:html||undefined,attachments:checked});res.status(202).json({ok:true});}catch(e){console.error('SMTP send error:',e.message);res.status(e.status||500).json({error:e.message});}});

if(!isVercel)app.listen(process.env.PORT||3001,()=>console.log(`Vedøy Mail API listening on ${process.env.PORT||3001}`));
export default app;
